### ISSUE TITLE
Submit to CRAN v0.1.0

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/aopdata#11]

**Comment by rafapereirabr** [comment]
Feedback from CRAN

> Thanks,
>
> Please always write package names, software names and API (application
programming interface) names in single quotes in title and description.
e.g: --> 'aopdata'
>
> Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
> Missing Rd-tags:
      aop_spatial_join.Rd: \value
      download_data.Rd: \value
      download_metadata.Rd: \value
      load_data.Rd: \value
      rm_accent.Rd: \value
      select_city_input.Rd: \value
      select_metadata.Rd: \value
      select_mode_input.Rd: \value
      select_year_input.Rd: \value
> 
> All your examples are wrapped in \donttest{} and therefore do not get
tested.
> 
> Please unwrap the examples if that is feasible and if they can be
executed in < 5 sec for each Rd file or create additionally small toy
examples to allow automatic testing.
> 
> You are setting options(warn=-1) in your function. This is not allowed.
Please rather use suppressWarnings() if really needed.
> 
>  Please fix and resubmit.
> 
> Best,
> Gregor Seyer

**Comment by rafapereirabr** [comment]
I've addressed all other issues, but I'm not sure I understand what the means with:

> "Please add \value to .Rd files regarding exported methods"

Do you guys know how we should address this? @dhersz

**Comment by dhersz** [comment]
All exported values should have a `@return` field in their documentation, which generates the `\value{}` field in the respective `.Rd` file. We just have to find the exported function(s) where `@return` is not specified and specify it.

**Comment by rafapereirabr** [comment]
> All exported values should have a `@return` field in their documentation, which generates the `\value{}` field in the respective `.Rd` file. We just have to find the exported function(s) where `@return` is not specified and specify it.

Oh, Ok then. I had done that already.
