### ISSUE TITLE
Problem connecting to data server when using {aopdata} functions

### ISSUE THREAD

**Issue by elisa-fink** [ipeaGIT/aopdata#57]
Olá

Baixei e carreguei o pacote `{aopdata}` no R com o seguinte código:

`install.packages("aopdata")
library("aopdata")`

quando tento utilizar funções como `read_population()`, recebo a seguinte mensagem de erro:

"Problem connecting to data server. Please try again in a few minutes."

Isso acontece sempre que utilizo um computador específico, em outros, não tenho o mesmo problema.
A internet está funcionando bem, e outros pacotes também funcionam normalmente.
O que poderia ser o problema nesse caso? Há algum outro requisito para a utilização das funções que não estou sabendo? (ex.: versão do R, instalação de outros pacotes/programas)

Agradeço desde já

**Comment by rafapereirabr** [comment]
Oi @elisa-fink . É muito curioso que esse problema ocorra apenas em um unico computador. Por favor, reinicie sua sessão de R no computador que tem dado problemas e rode esse código abaixo. Veja por favor se funciona.
```
utils::remove.packages('aopdata')

install.packages("aopdata")

library("aopdata")

df_for <- aopdata::read_population(city = 'Fortaleza')
head(df_for)
```

Se o problema persistir, rode `sessionInfo()` e cole o output num comentario abaixo.

**Comment by elisa-fink** [comment]
oi @rafapereirabr ,

Segue o output de `sessionInfo()`

````
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22000) 

Matrix products: default 
locale: [1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8 LC_MONETARY=Portuguese_Brazil.utf8
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.utf8
time zone: Etc/GMT+3
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] aopdata_1.0.2

loaded via a namespace (and not attached):
[1] httr_1.4.6        compiler_4.3.1    backports_1.4.1   R6_2.5.1          tools_4.3.1       curl_5.0.1        [7] data.table_1.14.8 checkmate_2.2.0 
> 
````

**Comment by rafapereirabr** [comment]
Oi Elisa. Nao consigo encontrar a razão de porque o erro persiste em um computador especifico.

Voce poderia tentar usando a versao dev?

```
utils::remove.packages('aopdata')
devtools::install_github("ipeaGIT/aopdata", subdir = "r-package")

library(aopdata)

df_for <- aopdata::read_population(city = 'Fortaleza')
head(df_for)
```

**Comment by rafapereirabr** [comment]
Oi @elisa-fink , isso foi resolvido com a ultima versao do pacote. Fechando aqui o issue, mas fique a vontade para reabri-lo se o problema persistir para voce
